1. How to check postgres is running or not
Ans-- By typing "ps -ef |grep postgres" command in OS level

2. How to check 5432 port number is active
Ans-- login psql and to know current port number type "select inet_server_port();" or \conninfo for full details database

3. How to make PostgreSQL to prompt for the password(Use pg_hba)


4. How to configure the .pgpass file


5. How to check the current database size

